### ISSUE TITLE
Jobs abuse

### ISSUE THREAD

**Issue by Laurentzius** [DAQEM/JobsPlusRemastered#8]
how to disable abuse jobs such as mining, digger, lumberjack, hunter. You can stand afk and two mouse buttons and pump up to the maximum. Is there a possibility of limiting the experience on 1 chunk? Also, is there a possibility to get experience only from ores and not from ordinary stone (diorite, andesite, cobblestone)?

**Comment by DAQEM** [comment]
The only thing you can do is override these files using a datapack: 
https://github.com/DAQEM/JobsPlusRemastered/blob/1.20.1/common/src/main/resources/data/jobsplus/arc/miner/break_uncommon_block.json
https://github.com/DAQEM/JobsPlusRemastered/blob/1.20.1/common/src/main/resources/data/jobsplus/arc/miner/break_common_block.json

I'm not gonna fix something just because people want to play like idiots.
